site_name: Genome Blog by the hCNV Community
site_description: 'Genome Blog by the hCNV Community'
site_author: Michael Baudis
copyright: ''
repo_name: 'genome-blog'
site_url: https://hcnv.github.io/genome-blog
repo_url: https://github.com/hcnv/genome-blog
edit_uri: edit/main/docs/

###############################################################################

nav:
  - Genome Blog: index.md
  - hCNV Community Home: http://cnvar.org

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: progenetix
      repo: progenetix-web
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

###############################################################################

theme:
  name: material
  palette:
    primary: indigo
  favicon: img/hCNV-logo.svg
  # logo: img/hCNV-logo.svg
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    # - navigation.instant
    # - navigation.tracking
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  custom_dir: overrides
      
plugins:
    - search
    - macros
    - mermaid2

extra:
  blog:
    dir: blog
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  social:
    # - icon: fontawesome/brands/twitter 
    #   link: https://twitter.com/progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/hcnv/genome-blog/tree/main/docs/blog
extra_css:
  - css/theme_overrides.css

    